### ISSUE TITLE
Licenciamiento- Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.

### ISSUE THREAD

**Issue by irenemonzon** [DemocraciaEnRed/leyesabiertas-web#108]
1-La herramienta no cuenta con licencia open source. Sugerimos revisar la web [https://choosealicense.com/](url)

**Comment by mishelpa** [comment]
- [x] Reunion con los encargados del proyecto.

- [x] Sugerir licencia openSource.

- [x] Elección de licencia MIT.

- [ ] Agregarlo en el README y crear el documento de LICENCIA en el repositorio

**Comment by guillecro** [comment]
Vamos a ir con GNU GPL v3.0

**Comment by guillecro** [comment]
Cierro el issue con la idea de que hemos cumplido con lo requerido tanto aqui como en https://github.com/DemocraciaEnRed/leyesabiertas
