### ISSUE TITLE
Documentación- Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.

### ISSUE THREAD

**Issue by irenemonzon** [DemocraciaEnRed/leyesabiertas-web#109]
Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de readme.md [https://github.com/EL-BID/Plantilla-de-repositorio/blob/master/README.md](url) hemos encontrado los siguiente puntos a mejorar:

1-Agregar el Nombre, descripción y contexto de la herramienta
2- Explicar uso de la herramienta
3- Mejorar la guía de instalación.(explicando mejor los paso, traducirlo a español)
4-Colocar los autores de la herramienta.
5- Agregar licencia a utilizar.

**Comment by mishelpa** [comment]
- [x]  Revisión del README.

- [x] Identificar los puntos de mejora.

Puntos de Mejora

- [x] **Descripción y contexto:** Descripción de las funcionalidades, el contexto donde fue desarrollado y los problemas de desarrollo que ayudó a resolver.

- [x] **Guía de usuario:** Paso a paso dirigido al usuario final sobre cómo empezar a usar la herramienta digital.

- [ ] **Guía de instalación:** Instrucciones de instalación para reutilizar y configurar la herramienta digital. (En proceso).

- [x] **Autores** Sección para dar créditos a los colaboradores de la herramienta.

- [ ] **Licencia para el código de la herramienta:** Permisos que se otorgan a terceros para reutilizar la herramienta digital.  https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

- [ ] **Licencia para la documentación de la herramienta:** Recomendamos el uso de las licencias creative commons para el licenciamiento de la documentación de las herramientas.

- [ ] **Cómo contribuir** Sección que explica a nuevos desarrolladores el proceso para contribuir a proyectos.

- [ ] **Código de conducta** El código de conducta establece las normas sociales, reglas y responsabilidades que los individuos y organizaciones deben seguir al interactuar de alguna manera con la herramienta digital o su comunidad. Es una buena práctica para crear un ambiente de respeto e inclusión en las contribuciones al proyecto. La plataforma Github premia y ayuda a los repositorios dispongan de este archivo. Al crear CODE_OF_CONDUCT.md puedes empezar desde una plantilla sugerida por ellos. 

- [ ] **Insignias (badges)** Las insignias (badges) pequeñas imágenes incrustadas en el README.md que especifican de una manera legible y concisa el estado de la herramienta. Existen insignias para el estado de desarrollo, el número de descargas, el versionado, sociales u otras. En este link podrás encontrar información https://shields.io/

- [ ] **Versión** Indica un listado de las versiones de las herramientas digital y las funcionalidades añadidas a cada versión.

**Comment by guillecro** [comment]
### NOTA
Todas estas apreciaciones se aplican en paralelo a los otros 3 modulos involucrados de la plataforma
- [https://github.com/DemocraciaEnRed/leyesabiertas-web](https://github.com/DemocraciaEnRed/leyesabiertas-web)
- [https://github.com/DemocraciaEnRed/leyesabiertas-core](https://github.com/DemocraciaEnRed/leyesabiertas-core)
- [https://github.com/DemocraciaEnRed/leyesabiertas-notifier](https://github.com/DemocraciaEnRed/leyesabiertas-notifier)

Acerca de la **guia para la instalacion**
Se agrego la guia en README y ademas se ha creado un repo aparte que engloba la informacion del proyecto:

- [https://github.com/DemocraciaEnRed/leyesabiertas](https://github.com/DemocraciaEnRed/leyesabiertas)

La ventaja es que cuenta con un docker-compose.yml para poder hacer una instalacion rapida en simple pasos.

Acerca de **version**
https://github.com/DemocraciaEnRed/leyesabiertas-web/releases

Acerca de **código de conducta** y **como contribuir**
No tenemos definido una mecanica actualmente, al mismo tiempo que la organizacion ni la Honorable Camara de Diputados no contempla que actores externos a la organizacion DER colaboren del proyecto.

Acerca de **Licencia para la documentacion de la herramienta**
No creo que aplique en este caso

Acerca de **Licencia para el código de la herramienta:**
Agregamos la correspondiente licencia.

**Comment by guillecro** [comment]
Cierro el issue con la idea de que hemos cumplido con lo requerido tanto aqui como en https://github.com/DemocraciaEnRed/leyesabiertas
