### ISSUE TITLE
Evaluación técnica- Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.

### ISSUE THREAD

**Issue by irenemonzon** [DemocraciaEnRed/leyesabiertas-web#110]
Al haber contrastado la información presentadas en el repo oficial hemos encontrado los siguiente puntos a mejorar:
1-Sugerimos revisar la herramienta en [https://sonarcloud.io/](url)
1-Agregar badge de imagen de docker en el repo.
2-Generar reportes de calidad de código.

**Comment by guillecro** [comment]
Hola, tenemos todo hecho, pero que se refieren con reportes de calidad de codigo?

**Comment by guillecro** [comment]
Cierro el issue con la idea de que hemos cumplido con lo requerido tanto aqui como en https://github.com/DemocraciaEnRed/leyesabiertas
