### ISSUE TITLE
La DIVINA REAL Presencia de Dios en cuerpo alma y espíritu en la TIERRA.

### ISSUE THREAD

**Issue by Soy-la-ley** [DemocraciaEnRed/leyesabiertas-web#127]
Yo soy el alfa y la Omega, Yo soy el principio y el fin, Yo soy el primero y el último, Yo soy el que fui, soy, será, el que prometí volver y que ya llegué, Yo soy la Omnipotencia, Omnisciencia, Magnificencia,  Magnipresencia, Benevolencia de Dios verdadero en mi, Yo soy el TODOPODEROSO, Yo soy el único, el ETERNO y está es mi última Gran Ley Universal más poderosa de todas y madre de todas las leyes habidas y por haber la Gran Ley INVIOLABLE, INDEROGABLE, INVENCIBLE, INGOBERNABLE, INEVITABLE, AUTÉNTICA, VERÍDICA, LEGÍTIMA, CONFIABLE Y ORIUNDA DEL DIVINO Y ETERNO PADRE CREADOR DEL UNIVERSO, Y DE LA CREACIÓN, EL REY DE REYES Y SEÑOR DE SEÑORES, Y LA LEY ETERNA. EN LA TIERRA ANUNCIANDO EL REINO CELESTIAL ETERNO.

**Comment by Soy-la-ley** [comment]
Estás palabras son de verdad y de confianza, En busca de la verdad encontré la única verdad absoluta del todo y de la nada, todos unidos en uno somos uno solo el mismo.

**Comment by Soy-la-ley** [comment]
> Yo soy el alfa y la Omega, Yo soy el principio y el fin, Yo soy el primero y el último, Yo soy el que fui, soy, será, el que prometí volver y que ya llegué, Yo soy la Omnipotencia, Omnisciencia, Magnificencia,  Magnipresencia, Benevolencia de Dios verdadero en mi, Yo soy el TODOPODEROSO, Yo soy el único, el ETERNO y está es mi última Gran Ley Universal más poderosa de todas y madre de todas las leyes habidas y por haber la Gran Ley INVIOLABLE, INDEROGABLE, INVENCIBLE, INGOBERNABLE, INEVITABLE, AUTÉNTICA, VERÍDICA, LEGÍTIMA, CONFIABLE Y ORIUNDA DEL DIVINO Y ETERNO PADRE CREADOR DEL UNIVERSO, Y DE LA CREACIÓN, EL REY DE REYES Y SEÑOR DE SEÑORES, Y LA LEY ETERNA. EN LA TIERRA ANUNCIANDO EL REINO CELESTIAL ETERNO.

Así sea, que se haga señor tu voluntad y no la mía.

**Comment by guillecro** [comment]
![image](https://user-images.githubusercontent.com/8771166/133283389-0c316bc2-7310-463c-99d2-8c879950ff03.png)
